[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cam-synth"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pyglet",
    "pyrender",
    "trimesh",
    "pydantic>=2.0",
    "opencv-python",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
    "pre-commit",
]

[tool.black]
line-length = 120
target-version = ["py310"]
